spring:
  application:
    name: ScheduleRecall
  datasource:
    url: jdbc:mysql://localhost:3306/vish
    username: root
    password: vish
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
#Eureka Client
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# Additional Spring Boot configuration properties...
logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql: INFO