spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vish
    username: root
    password: vish
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
# Additional Spring Boot configuration properties...
logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql: INFO